name: Update Raw From Google Sheet

on:
  schedule:
    - cron: "*/10 * * * *"   # har 10 minute
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Google Sheet as CSV
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1sWFK8XP0iXAO7nwfbJ3YQ_HnfDkvHhIcCf2RvQ9lbc0/export?format=csv" -o output.csv

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update from Google Sheet"
          git push
