name: Update Raw From Google Sheet

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reset repo to remote main
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Download Google Sheet as CSV
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1sWFK8XP0iXAO7nwfbJ3YQ_HnfDkvHhIcCf2RvQ9lbc0/export?format=csv" -o output.csv

      - name: Commit and force push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add output.csv

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto sync from Google Sheet"
            git push origin main --force
          fi
